"""Configuration parameters for this example."""

RNG_SEED = 1001209834
NUM_SIMULATORS = 8
SIMULATION_TIME = 30
SAMPLING_FREQUENCY = 5
CONTROL_FREQUENCY = 60
DATABASE_FILE = "results/run0.sqlite"
INITIAL_STD = 0.5
NUM_GENERATIONS = 100
