name: mypy

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      python_version:
        required: true
        type: string

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dev_requirements.txt
        run: pip install -r ./requirements_dev.txt
      - name: Run mypy
        run: ./codetools/mypy/check.sh ./examples/${{ inputs.directory }}
